title: Voicity Agency
domain: 'https://voicity.agency'
url: https://voicity.agency
baseurl: /
permalink: '/:title/'

# Collections
# ========================================================================================
collections:
  posts:
    permalink: '/blog/posts/:title/'
    output:            true

base_font: nunito-sans
palette: cyan
header:
  logo_img: images/voicity_logo.svg
  logo_img_alt: Logo
  has_nav: true
  nav_links:
    - label: Inicio
      url: /
      style: link
    - label: Servicios
      url: /features
      style: link
    # - label: Pricing
    #   url: /pricing
    #   style: link
    - label: Sobre nosotros
      url: /about
      style: link
    - label: Blog
      url: /blog
      style: link
    # - label: Style Guide
    #   url: /style-guide
    #   style: link
    # - label: Sign Up
    #   url: /signup
    #   style: primary
    - label: Contacto
      url: /contact
      style: primary
footer:
  sections:
    - type: footer_text
      image: images/logo-alt.svg
      image_url: /
      image_alt: Footer logo
      content: Stackbit theme demo
    - type: footer_nav
      title: Company
      nav_links:
        - label: Sobre nosotros
          url: /about
          style: link
        - label: Blog
          url: /blog
          style: link
        # - label: Sign Up
        #   url: /signup
        #   style: link
        - label: Contact
          url: /contact
          style: link
    - type: footer_nav
      title: Community
      nav_links:
        - label: Twitter
          url: 'https://twitter.com/'
          style: link
          has_icon: true
          icon: twitter
          icon_position: left
        - label: LinkedIn
          url: 'https://www.linkedin.com/'
          style: link
          has_icon: true
          icon: linkedin
          icon_position: left
        - label: GitHub
          url: 'https://github.com/'
          style: link
          has_icon: true
          icon: github
          icon_position: left
        - label: Medium
          url: 'https://github.com/'
          style: link
          has_icon: true
          icon: medium
          icon_position: left
    - type: footer_form
      title: Subscribe
      content: Stay up to date with our latest developments.
      form_id: contactForm
      hide_labels: true
      form_fields:
        - input_type: email
          name: email
          label: Email
          default_value: Enter email address
          is_required: true
      submit_label: Subscribe
  has_nav: true
  nav_links:
    - label: Terms of Service
      url: /terms-of-service
      style: link
    - label: Privacy Policy
      url: /privacy-policy
      style: link
  content: >-
    Made with ❤ by Voicity Agency © 2021. All rights reserved.
sass:
  indentWidth: 4
  style: nested
  precision: 10
# Other Plugins
# ---------------------------------------------------------------------------------------


# Used for Facebook open graph
# facebook:
#   app_id:              <id>
#   publisher:           <id>
#   admins:              <id>

# Used on index and about sites

optional_front_matter:
  remove_originals:    true

readme_index:
  remove_originals:    true
  with_frontmatter:    true

relative_links:
  collections:         true

titles_from_headings:
  strip_title:         true
  collections:         true

plugins:
  - jekyll-menus
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-analytics

jekyll_analytics:
  GoogleAnalytics: 
    id: UA-192090095-1


# File inclusion/exclusion
# ========================================================================================
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js

