title: Voicity Agency
domain: 'https://voicity.agency'
url: https://voicity.agency
baseurl: /
permalink: '/:title/'

# Collections
# ========================================================================================
collections:
  posts:
    permalink: '/blog/posts/:title/'
    output:            true
favicon: images/favicon.png
base_font: nunito-sans
palette: cyan
header:
  logo_img: images/voicity_logo.png
  logo_img_alt: Logo
  has_nav: true
  nav_links:
    - label: Inicio
      url: /
      style: link
    - label: Ayuntamientos
      url: /ayuntamientos
      style: link
    - label: Servicios
      url: /features
      style: link
    # - label: Pricing
    #   url: /pricing
    #   style: link
    - label: Sobre nosotros
      url: /about
      style: link
    - label: Blog
      url: /blog
      style: link
    # - label: Style Guide
    #   url: /style-guide
    #   style: link
    # - label: Sign Up
    #   url: /signup
    #   style: primary
    - label: Contacto
      url: /contact
      style: primary
footer:
  sections:
    - type: footer_text
      image: images/voicity_logo_footer.png
      image_url: /
      image_alt: Footer logo
      # content: Voicity Agency
    - type: footer_nav
      title: Agencia
      nav_links:
        - label: Sobre nosotros
          url: /about
          style: link
        - label: Blog
          url: /blog
          style: link
        # - label: Sign Up
        #   url: /signup
        #   style: link
        - label: Contacto
          url: /contact
          style: link
    - type: footer_nav
      title: Síguenos en
      nav_links:
        - label: Twitter
          url: 'https://twitter.com/voicityagency'
          style: link
          has_icon: true
          icon: twitter
          icon_position: left
        - label: LinkedIn
          url: 'https://www.linkedin.com/company/voicityagency'
          style: link
          has_icon: true
          icon: linkedin
          icon_position: left
        - label: GitHub
          url: 'https://github.com/voicityagency'
          style: link
          has_icon: true
          icon: github
          icon_position: left
        - label: Medium
          url: 'https://medium.com/voicityagency'
          style: link
          has_icon: true
          icon: medium
          icon_position: left
    - type: footer_form
      title: Newsletter
      content: Mantente al día de nuestras últimas novedades y desarrollos.
      form_id: subcriptionForm
      form_action: https://www.getrevue.co/profile/voicityagency/add_subscriber
      hide_labels: true
      form_fields:
        - input_type: email
          name: member[email]
          label: Email
          default_value: Correo electrónico
          is_required: true
      submit_label: Suscríbete
  has_nav: true
  nav_links:
    - label: Uso de Cookies
      url: /cookies
      style: link
    - label: Política de Privacidad
      url: /privacy-policy
      style: link
  content: >-
    Hecho con ❤ por Voicity Agency © 2021. Reservados todos los derechos.
sass:
  indentWidth: 4
  style: nested
  precision: 10
# Other Plugins
# ---------------------------------------------------------------------------------------


# Used for Facebook open graph
# facebook:
#   app_id:              <id>
#   publisher:           <id>
#   admins:              <id>

# Used on index and about sites

optional_front_matter:
  remove_originals:    true

readme_index:
  remove_originals:    true
  with_frontmatter:    true

relative_links:
  collections:         true

titles_from_headings:
  strip_title:         true
  collections:         true

plugins:
  - jekyll-menus
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-analytics
  - jekyll-spaceship

jekyll_analytics:
  GoogleAnalytics: 
    id: UA-192090095-1


# File inclusion/exclusion
# ========================================================================================
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js

